// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6h8XUph5lG1cHZM9-cIpva1Dr_KzbSOg',
    appId: '1:293295507422:web:e546402e3a8c66b5b6bf4f',
    messagingSenderId: '293295507422',
    projectId: 'fir-project-adef9',
    authDomain: 'fir-project-adef9.firebaseapp.com',
    storageBucket: 'fir-project-adef9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_Bl4dUVKKSXNkdjVxjwEJKJXJTs3asTU',
    appId: '1:293295507422:android:68c8e19eca7edf3eb6bf4f',
    messagingSenderId: '293295507422',
    projectId: 'fir-project-adef9',
    storageBucket: 'fir-project-adef9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEEUmoFhzAaujQdU52Y0ojMIaIdBME61Q',
    appId: '1:293295507422:ios:9ef673e9fba0aa08b6bf4f',
    messagingSenderId: '293295507422',
    projectId: 'fir-project-adef9',
    storageBucket: 'fir-project-adef9.firebasestorage.app',
    iosBundleId: 'com.google.firebase.presents.firebasedemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEEUmoFhzAaujQdU52Y0ojMIaIdBME61Q',
    appId: '1:293295507422:ios:9ef673e9fba0aa08b6bf4f',
    messagingSenderId: '293295507422',
    projectId: 'fir-project-adef9',
    storageBucket: 'fir-project-adef9.firebasestorage.app',
    iosBundleId: 'com.google.firebase.presents.firebasedemo',
  );
}
